# Generated by Django 4.2.13 on 2024-07-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs'},
        ),
    ]
