# Generated by Django 4.2.13 on 2024-07-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter list'},
        ),
    ]
